language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov coveralls responses coveralls
# command to run tests
script:
  - pytest --cov=eero eero/tests/*
  - coveralls
